### PR TITLE
Better db schema

### PR DESCRIPTION
**Pull request by quilesbaker**

### CODE REVIEW

**Comment by quilesbaker** [comment]
WIP. just as an update and maybe some insight / help.

**Comment by quilesbaker** [comment]
TODO: redefine services sql queries to retrieve data from multiple tables instead of one.

**Comment by quilesbaker** [comment]
For implementation so far:

Pros:
- divided model in multiple tables
- lazy loading of csv processing (not putting all csv file into memory at once).

Cons:
- inpections_violations table has too many rows
- lazy loading of csv loads and processes one line at a time (including 1 row insert at a time to db)

Basically, instead of lazy loading one row of the csv file at a time, it would be ideal to load a couple of them that fit easily into memory and then process multi. This would be better than loading all entries (currently on master) and one at a time (currently on this PR).

I want to discuss the use case of retrieving data from the api for violations (do we care to filter only by a specific violation number? do we want to find all violations for one restaurant?, etc) to make sure we use the best model possible for storing them. Before, we were using 58 columns on a table. Currently on PR, there's one row per each violation per each inspection, which amounts to a lot of rows very quickly.

**Comment by leordev** [comment]
Thank you @quilesbaker for your wonderful job here 😆 
I will rebuild the api endpoints with the new schema!
Now it's on me, I will use this same branch to continue the updates!

**Comment by quilesbaker** [comment]
@leordev this is looking good. Travis checks have failed. Haven't checked but might be either build or tests failure.

**Comment by quilesbaker** [comment]
Yeah just noticed the issue is the services test. Some functions are not defined. I'm not sure if to remove them or what. Let me know :)

**Comment by quilesbaker** [comment]
@leordev should I just remove the failing tests from services?

**Comment by leordev** [comment]
yes it’s fine you can do that! ;)

**Pull request merged**
